version: '3'

services:

  frontend:
    build: ./frontend
    image: multiblog-frontend
    container_name: multiblog-frontend
    command: npm run dev
    volumes:
        - ./frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    image: multiblog-backend
    container_name: multiblog-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
        - ./backend:/backend
    ports: 
      - "8000:8000"
    env_file:
      ./.env
    depends_on:
      - db
  
  db:
    image: postgres:15
    container_name: multiblog-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: mydatabaseuser
      POSTGRES_PASSWORD: mypassword

volumes:
  postgres_data:

